version: 2.0

## Shared definitions

_conda37: &conda37
  step:
    name: Create Python 3.7 conda environment
    command: conda create -yv -n idaes python=3.7

_conda36: &conda36
  step:
    name: Create Python 3.6 conda environment
    command: conda create -yv -n idaes python=3.6

_pytest: &pytest
  step:
    name: Install extensions and run tests in Python conda environment
    command: |
      source activate idaes
      python -m pip install --progress-bar=off -r requirements.txt
      idaes get-extensions
      pytest -c pytest.ini idaes -m "not nocircleci"

_clone_examples: &clone_examples
  step:
    name: Clone examples-dev
    command: git clone git@github.com:IDAES/examples-dev.git

_test_examples: &test_examples
  step:
    name: Run examples-dev tests
    command: |
      source activate idaes
      cd examples-dev
      pytest -m "not integration"

_vars:
  - &ubuntu-image idaes/ubuntu18-conda:2.0

## Jobs

jobs:
  # Python 3.6 non-developer
  python36:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *conda36
      - <<: *pytest

  # Python 3.7 non-developer
  python37:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *conda37
      - <<: *pytest

  # Python 3.7 examples
  examples37:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *conda37
      - <<: *pytest
      - <<: *clone_examples
      - <<: *test_examples

  "pip-install":
    docker:
      - image: *ubuntu-image
    working_directory: ~
    steps:
      - <<: *conda37
      - run:
          name: Install idaes-pse
          command: |
            source activate idaes
            python -m pip install idaes-pse
      - run:
          name: Install idaes extensions
          command: |
            source activate idaes
            idaes get-extensions
      - run:
          name: Run tests
          command: |
            source activate idaes
            pytest --pyargs idaes -W ignore


workflows:
  version: 2
  build:
    jobs:
      - python36
      - python37
      - examples37
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
                - nightlies
    jobs:
      - "pip-install"


#shared-dev: &shared-dev
#  working_directory: ~/repo
#  steps:
#    - checkout
#    - run: ./scripts/remove-idaes-from-path.sh
#    - run: pip install --progress-bar=off -r requirements-dev.txt
#    - run: pylint -E --ignore-patterns="test_.*" idaes || true
#    - run: cd docs && python build.py
#    - run: idaes get-extensions
#    - run: pytest -c pytest-dev.ini idaes -m "not nocircleci"
#    - run: coverage xml
#    - run: coveralls
#
#shared: &shared
#  working_directory: ~/repo
#  steps:
#    - checkout
#    - run: ./scripts/remove-idaes-from-path.sh
#    - run: pip install --progress-bar=off -r requirements.txt
#    - run: idaes get-extensions
#    - run: pytest -c pytest.ini idaes -m "not nocircleci"
#
#shared-ex: &shared-ex
#  working_directory: ~/repo
#  steps:
#
