version: 2.1

## Shared definitions

# Notes:
# - use "source activate" instead of "conda activate" since conda init bash
#

_install: &install
  run:
    name: Install idaes and extensions
    command: |
        source activate idaes
        pip --no-cache-dir install --progress-bar off .
        idaes get-extensions --platform ubuntu1804

_install_dev: &installdev
  run:
    name: Install idaes and extensions
    command: |
        source activate idaes
        pip --no-cache-dir install --progress-bar off .[dev]
        idaes get-extensions --platform ubuntu1804

_pytest: &pytest
  run:
    name: Run tests
    command: |
        source activate idaes
        pytest -c pytest.ini idaes -m "not nocircleci"

_docs: &build_docs
  run:
      name: Build Sphinx documentation
      command: |
          source activate idaes
          cd docs
          python build.py

_clone_examples: &clone_examples
  run:
    name: Clone examples-dev
    command: git clone git@github.com:IDAES/examples-dev.git

_test_examples: &test_examples
  run:
    name: Run examples-dev tests
    command: |
      source activate idaes
      cd examples-dev
      pytest -m "not integration"

_pylint: &pylint
  run:
    name: pylint
    command: pylint -E --ignore-patterns="test_.*" idaes || true

_coverage: &coverage
  run:
    name: Code coverage
    command: |
        coverage xml
        coveralls

_vars:
  - &ubuntu-image idaes/ubuntu18-conda:2.0

## Commands (new in 2.1)

commands:
  setup_env:
    description: Set up shared environment variables
    steps:
      - run:
          command: |
            echo "export LANG=C.UTF-8" >> $BASH_ENV
            echo "export LC_ALL=C.UTF-8" >> $BASH_ENV
  create_conda:
    description: Create Python conda environment
    parameters:
      version:
        type: string
        default: "3.7"
    steps:
      - run: conda create -yv -n idaes python=<< parameters.version >>

## Jobs

jobs:
  # Python 3.6 non-developer
  python36:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - setup_env
        - create_conda:
            version: "3.6"
        - <<: *install
        - <<: *pytest
        - <<: *pylint

  # Python 3.7 non-developer
  python37:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - setup_env
        - create_conda:
            version: "3.7"
        - <<: *install
        - <<: *pytest
        - <<: *pylint

  # Python 3.7 developer install
  python37dev:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - setup_env
        - create_conda:
            version: "3.7"
        - <<: *installdev
        - <<: *pytest
        - <<: *build_docs
        - <<: *pylint
        - <<: *coverage

  # Python 3.7 examples
  examples37:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - setup_env
        - create_conda:
            version: "3.7"
        - <<: *install
        - <<: *clone_examples
        - <<: *test_examples

  # pip install-based
  "pip-install":
    docker:
      - image: *ubuntu-image
    working_directory: ~
    steps:
      - setup_env
      - create_conda:
          version: "3.7"
      - run:
          name: Install idaes-pse
          command: |
            source activate idaes
            python -m pip install idaes-pse
      - run:
          name: Install idaes extensions
          command: |
            source activate idaes
            idaes get-extensions
      - run:
          name: Run tests
          command: |
            source activate idaes
            pytest --pyargs idaes -W ignore

## Workflows

workflows:
  version: 2
  build:
    jobs:
        - python36
        - python37
        - python37dev
        - examples37
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
                - nightlies
    jobs:
      - "pip-install"
