version: 2.0

shared-dev: &shared-dev
  working_directory: ~/repo
  steps:
    - checkout
    - run: ./install-solvers.sh
    - run: sudo pip install pip==18.0.0
    - run: sudo pip install -r requirements-dev.txt
    - run: pyomo --version
    - run: cd docs && make all
    - run: pytest -c pytest-dev.ini docs idaes -m "not nocircleci"
    - run: coverage report
    - run: coveralls

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: ./install-solvers.sh
    - run: sudo pip install pip==18.0.0
    - run: sudo pip install -r requirements.txt
    - run: pytest -c pytest.ini idaes -m "not nocircleci"

jobs:
  "python-3.7":
    docker:
      - image: circleci/python:3.7
    <<: *shared
  "python-3.7-dev":
    docker:
      - image: circleci/python:3.7
    <<: *shared-dev

workflows:
  version: 2
  build:
    jobs:
      - "python-3.7"
