version: 2.0

shared-dev: &shared-dev
  working_directory: ~/repo
  steps:
    - checkout
    - run: ./scripts/remove-idaes-from-path.sh
    - run: pip install pip==18.0.0
    - run: pip install -r requirements-dev.txt
    - run: pyomo --version
    - run: cd docs && make all
    - run: pytest -c pytest-dev.ini docs idaes -m "not nocircleci"
    - run: coverage report
    - run: coveralls

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: ./scripts/remove-idaes-from-path.sh
    - run: pip install pip==18.0.0
    - run: pip install -r requirements.txt
    - run: pylint -E --ignore-patterns="test_.*" idaes || true
    - run: pytest -c pytest.ini idaes -m "not nocircleci"

jobs:
  "python-3.7":
    docker:
      - image: idaes/jupyterhub:latest
    <<: *shared
  "python-3.7-dev":
    docker:
      - image: idaes/jupyterhub:latest
    <<: *shared-dev

workflows:
  version: 2
  build:
    jobs:
      - "python-3.7"
