version: 2.1

# Notes:
# - use "source activate" instead of "conda activate" since conda init bash
#   does not seem to "take".

_vars:
  - &ubuntu-image idaes/ubuntu18-conda:2.0

## Commands shared by jobs

commands:
  setup_env:
    description: Set up shared environment variables
    steps:
      - run:
          command: |
            echo "export LANG=C.UTF-8" >> $BASH_ENV
            echo "export LC_ALL=C.UTF-8" >> $BASH_ENV
  create_conda:
    description: Create Python conda environment
    parameters:
      python_version:
        type: string
        default: "3.7"
    steps:
      - run: conda create -yv -n idaes python=<<parameters.python_version>>
  install:
    description: Install idaes and extensions
    parameters:
      pip_target:
        type: string
        default: "."
    steps:
      - run:
          command: |
              source activate idaes
              pip --no-cache-dir install --progress-bar off <<parameters.pip_target>>
              idaes get-extensions --platform ubuntu1804
  pytest:
    description: Run tests with pytest
    parameters:
      tags:
        type: string
        default: "not nocircleci"
    steps:
      - run:
          command: |
              source activate idaes
              pytest -c pytest.ini idaes -m "<<parameters.tags>>"
  build_docs:
    description: Build Sphinx documentation
    steps:
      - run:
          command: |
              source activate idaes
              cd docs
              python build.py
  examples:
    description: Run tests from examples-dev master
    steps:
      - run:
          name: Clone examples-dev
          command: git clone git@github.com:IDAES/examples-dev.git
      - run:
          name: Run examples-dev tests
          command: |
            source activate idaes
            cd examples-dev
            pytest -m "not integration"
  pylint:
    description: Run pylint
    steps:
      - run: pylint -E --ignore-patterns="test_.*" idaes || true
  coverage:
    description: Report code coverage
    steps:
      - run: coverage xml && coveralls
  idaes_pse:
    description: Install and test idaes-pse
    steps:
      - run:
          name: Install idaes-pse
          command: |
            source activate idaes
            python -m pip install idaes-pse
      - run:
          name: Install idaes extensions
          command: |
            source activate idaes
            idaes get-extensions
      - run:
          name: Run tests
          command: |
            source activate idaes
            pytest --pyargs idaes -W ignore

## Jobs

jobs:
  idaes_dev:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    parameters:
      python_version:
        type: string
        default: "3.7"
      pip_target:
        type: string
        default: "."
      devmode:
        type: boolean
        default: false
    steps:
        - checkout
        - setup_env
        - create_conda
        - install
        - pytest
        - pylint
        - when:
            condition: <<parameters.devmode>>
            steps:
              - build_docs
              - coverage

  # Clone and test examples
  examples_dev:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    parameters:
      python_version:
        type: string
        default: "3.7"
    steps:
        - checkout
        - setup_env
        - create_conda
        - install
        - clone_examples
        - test_examples

  # pip install-based
  idaes_pse:
    docker:
      - image: *ubuntu-image
    working_directory: ~
    parameters:
      python_version:
        type: string
        default: "3.7"
    steps:
      - setup_env
      - create_conda:
          version: <<parameters.python_version>>
      - idaes_pse

## Workflows

workflows:
  version: 2
  build:
    jobs:
        - idaes_dev:
            python_version: "3.6"
        - idaes_dev:
            python_version: "3.7"
        - idaes_dev:
            python_version: "3.7"
            pip_target: ".[dev]"
            devmode: true
        - examples_dev:
            python_version: "3.6"
        - examples_dev:
            python_version: "3.7"
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
                - nightlies
    jobs:
      - idaes_pse:
          python_version: "3.6"
      - idaes_pse:
          python_version: "3.7"
