version: 2.1

# Notes:
# - use "source activate" instead of "conda activate" since conda init bash
#   does not seem to "take".

_vars:
  - &ubuntu-image idaes/ubuntu18-conda:2.1

## Commands shared by jobs

commands:
  setup_env:
    description: Set up shared environment variables
    steps:
      - run:
          name: "Set locale to 'C.UTF-8'"
          command: |
            echo "export LANG=C.UTF-8" >> $BASH_ENV
            echo "export LC_ALL=C.UTF-8" >> $BASH_ENV
  create_conda:
    description: Create Python conda environment
    parameters:
      python_version:
        type: string
    steps:
      - run: conda create -yv -n idaes python=<<parameters.python_version>>
  install:
    description: Install idaes and extensions
    parameters:
      target:
        type: string
    steps:
      - run:
          name: Install from source tree
          command: |
              source activate idaes
              pip --no-cache-dir install --progress-bar off git+https://github.com/PyUtilib/pyutilib git+https://github.com/IDAES/pyomo.git@IDAES
              pip --no-cache-dir install --progress-bar off -e <<parameters.target>>
              idaes get-extensions --platform ubuntu1804
  pytest:
    description: Run tests with pytest
    parameters:
      tags:
        type: string
        default: "not integration"
    steps:
      - run:
          name: Run pytest
          command: |
              source activate idaes
              pytest -c pytest.ini idaes -m "<<parameters.tags>>"
  pytest_cov:
    description: Run tests with pytest
    parameters:
      tags:
        type: string
        default: "not integration"
    steps:
      - run:
          name: Run pytest
          command: |
              source activate idaes
              pytest -c pytest.ini idaes --cov -m "<<parameters.tags>>"
  build_docs:
    description: Build Sphinx documentation
    steps:
      - run:
          name: Build Sphinx docs
          command: |
              source activate idaes
              cd docs
              python build.py
  integration:
    description: Run integration tests, including examples
    steps:
      - run:
          name: Clone examples-dev
          command: git clone "https://idaes-build:${IDAESBUILDPASS}@github.com/IDAES/examples-dev.git"
      - run:
          name: Run integration tests, maybe
          command: |
            export PR=$(echo $CIRCLE_PULL_REQUEST | cut -f7 -d'/')
            printf "Looking for PR #${PR}..\n"
            export found=yes
            grep -q ${PR} .circleci/approved_pr.txt || found=no
            if [ ${found} = yes ]; \
            then \
              printf "*********************************************************************\n"; \
              printf "* PR #${PR} is marked as approved. Running integration tests...\n"; \
              printf "*********************************************************************\n"; \
              source activate idaes; \
              pytest -m integration idaes; \
              cd examples-dev; \
              pytest;  \
            else \
              printf "*********************************************************************\n"; \
              printf "* Not running integration tests as PR #${PR} is not marked as approved\n"; \
              printf "*\n"; \
              printf "*   If you want to run them, add a line \"$PR\" (no quotes)\n"; \
              printf "*   to the file '.circleci/approved_pr.txt'\n"; \
              printf "*   and commit and push the result to your PR\n"; \
              printf "*\n"; \
              printf "*********************************************************************\n"; \
            fi
  pylint:
    description: Run pylint
    steps:
      - run:
          name: pylint
          command: pylint -E --ignore-patterns="test_.*" idaes || true
  coverage:
    description: Report code coverage
    steps:
      - run:
          name: coverage
          command: |
              source activate idaes
              coverage xml
              coveralls
  idaes_pse:
    description: Install and test idaes-pse
    steps:
      - run:
          name: Install idaes-pse
          command: |
            source activate idaes
            python -m pip install --progress-bar=off idaes-pse
      - run:
          name: Install idaes extensions
          command: |
            source activate idaes
            idaes get-extensions --platform ubuntu1804 --verbose
            ipopt -v
      - run:
          name: Run tests
          command: |
            source activate idaes
            pytest --pyargs idaes -W ignore

## Jobs

jobs:
  idaes_dev:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    parameters:
      python:
        type: string
        default: "3.7"
      pip_target:
        type: string
        default: "."
      devmode:
        type: boolean
        default: false
    steps:
        - checkout
        - setup_env
        - create_conda:
            python_version: << parameters.python >>
        - install:
            target: << parameters.pip_target >>
        - when:
            condition: <<parameters.devmode>>
            steps:
                - pytest_cov
        - unless:
            condition: <<parameters.devmode>>
            steps:
                - pytest
        - pylint
        - when:
            condition: <<parameters.devmode>>
            steps:
              - build_docs
              - coverage

  # Clone and test examples
  integration_tests:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    parameters:
      python:
        type: string
        default: "3.7"
    steps:
        - checkout
        - setup_env
        - create_conda:
            python_version: << parameters.python >>
        - install:
            target: "."
        - integration

  # pip install-based
  idaes_pse:
    docker:
      - image: *ubuntu-image
    working_directory: ~
    parameters:
      python:
        type: string
        default: "3.7"
    steps:
      - setup_env
      - create_conda:
          python_version: << parameters.python >>
      - idaes_pse

## Workflows

workflows:
  version: 2.1
  pull_request:
    jobs:
        - idaes_dev:
            context: IDAES
            name: "python3.6"
            python: "3.6"
        - idaes_dev:
            context: IDAES
            name: "python3.7"
            python: "3.7"
        - idaes_dev:
            context: IDAES
            name: "python3.8"
            python: "3.8"
        - idaes_dev:
            context: IDAES
            name: "python3.7 dev"
            python: "3.7"
            pip_target: ".[dev]"
            devmode: true
        - integration_tests:
            context: IDAES
            name: "integration3.6"
            python: "3.6"
        - integration_tests:
            context: IDAES
            name: "integration3.7"
            python: "3.7"
        - integration_tests:
            context: IDAES
            name: "integration3.8"
            python: "3.8"
  nightly:
    triggers:
      - schedule:
          cron: "0 0,6,12,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - idaes_dev:
          context: IDAES
          python: "3.6"
      - idaes_dev:
          context: IDAES
          python: "3.7"
