version: 2.0

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: sudo apt-get update && sudo apt-get install -y libboost-dev
    - run: wget https://ampl.com/netlib/ampl/solvers.tgz
    - run: tar -xf solvers.tgz
    - run: cd solvers && ./configure
    - run: cd solvers && make
    - run: export ASL_BUILD=home/circleci/repo/solvers/sys.x86_64.Linux && cd idaes/property_models/iapws95 && make
    - run: sudo pip install -qr requirements.txt
    - run: sudo python setup.py -q install
    - run: cd doc && make dep html
    - run: pytest idaes -m "not nocircleci"
    - run: codecov --token=5cf93a40-daf7-4893-a28a-0d1cf229d110

jobs:
  "python-2.7":
    docker:
      - image: circleci/python:2.7
    <<: *shared

  "python-3.6":
    docker:
      - image: circleci/python:3.6
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
