version: 2.0

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: ./install-solvers.sh
    - run: sudo pip install pip==18.0.0
    - run: sudo pip install -qr requirements.txt
    - run: pyomo --version
    - run: sudo python setup.py -q install
    - run: cd docs_rst && make html
    - run: cd docs_rst && make doctest
    - run: pytest idaes -m "not nocircleci"
    - run: coverage report
    - run: coveralls
jobs:
  "python-3.6":
    docker:
      - image: circleci/python:3.6
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "python-3.6"
