version: 2.0

shared: &shared
  working_directory: ~/repo
  steps:
    - checkout
    - run: sudo pip install -qr requirements.txt
    - run: sudo python setup.py -q install
# Skip doc build until we move them over
#    - run: cd doc && make dep html
    - run: pytest idaes -m "not nocircleci"
 
# Skip codecov for now
#    - run: codecov --token=c786fe92-e199-484a-a586-b97ade166385
      
jobs:
  "python-2.7":
    docker:
      - image: circleci/python:2.7
    <<: *shared

  "python-3.6":
    docker:
      - image: circleci/python:3.6
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
