version: 2.0

## Shared definitions

_conda37: &conda37
  run:
    name: Create Python 3.7 conda environment
    command: conda create -yv -n idaes python=3.7

_conda36: &conda36
  run:
    name: Create Python 3.6 conda environment
    command: conda create -yv -n idaes python=3.6

_install: &install
  run:
    name: Install idaes and extensions
    command: |
        source activate idaes
        export LC_ALL=C.UTF-8 LANG=C.UTF-8
        python -m pip install --progress-bar=off -r requirements.txt
        idaes get-extensions --platform ubuntu1804
        export PATH=$HOME/.idaes/bin:$PATH
        export LD_LIBRARY_PATH=$HOME/.idaes/lib
        pytest -c pytest.ini idaes -m "not nocircleci"

_pytest: &pytest
  run:
    name: Run tests
    command: |
        source activate idaes
        export LC_ALL=C.UTF-8 LANG=C.UTF-8
        export PATH=$HOME/.idaes/bin:$PATH
        export LD_LIBRARY_PATH=$HOME/.idaes/lib
        pytest -c pytest.ini idaes -m "not nocircleci"

_clone_examples: &clone_examples
  run:
    name: Clone examples-dev
    command: git clone git@github.com:IDAES/examples-dev.git

_test_examples: &test_examples
  run:
    name: Run examples-dev tests
    command: |
      source activate idaes
      cd examples-dev
      pytest -m "not integration"

_pylint: &pylint
  run:
    name: pylint
    command: pylint -E --ignore-patterns="test_.*" idaes || true

_coverage: &coverage
  run:
    name: Code coverage
    command: |
        coverage xml
        coveralls

_vars:
  - &ubuntu-image idaes/ubuntu18-conda:2.0

## Jobs

jobs:
  # Python 3.6 non-developer
  python36:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - <<: *conda36
        - <<: *install
        - <<: *pytest

  # Python 3.7 non-developer
  python37:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - <<: *conda37
        - <<: *install
        - <<: *pytest

  # Python 3.7 developer
  python37dev:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - <<: *conda37
        - <<: *install
        - <<: *pytest
        - <<: *pylint
        - <<: *coverage

  # Python 3.7 examples
  examples37:
    docker:
      - image: *ubuntu-image
    working_directory: ~/repo
    steps:
        - checkout
        - <<: *conda37
        - <<: *install
        - <<: *pytest
        - <<: *clone_examples
        - <<: *test_examples

  # pip install-based
  "pip-install":
    docker:
      - image: *ubuntu-image
    working_directory: ~
    steps:
      - <<: *conda37
      - run:
          name: Install idaes-pse
          command: |
            source activate idaes
            python -m pip install idaes-pse
      - run:
          name: Install idaes extensions
          command: |
            source activate idaes
            idaes get-extensions
      - run:
          name: Run tests
          command: |
            source activate idaes
            pytest --pyargs idaes -W ignore

## Workflows

workflows:
  version: 2
  build:
    jobs:
        - python36
        - python37
        - python37dev
        - examples37
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
                - nightlies
    jobs:
      - "pip-install"
