name: Run IDAES examples
description: Run IDAES examples

inputs:

  reinstall-target:
    description: Installation variant or pip install arguments to use to install IDAES
    required: true

  examples-repository:
    description: Full name (owner/repo) of the repository to use for the examples
    required: false
    default: IDAES/examples

  examples-ref:
    description: git ref to use for the examples
    required: false
    default: main

  notebook-cell-exec-timeout:
    description: Maximum time in s allowed for each individual notebook cell to execute before an error is raised
    required: true

  working-dir:
    description: Working directory where the examples will be run
    required: false
    default: ${{ runner.temp }}

runs:
  using: composite
  steps:

    - name: Install examples repository as Python package
      # -l needed to be able to run this step correctly within a Conda environment
      shell: bash -l {0}
      env:
        PIP_PROGRESS_BAR: "off"
        _pip_install_url: https://github.com/${{ inputs.examples-repository }}@${{ inputs.examples-ref }}
      run: |
        pip install "idaes_examples[jb] @ git+${_pip_install_url}"
        # uninstall IDAES if installed through idaes_examples so that the version under test can be used
        pip uninstall --yes ides-pse

    - name: Reinstall IDAES
      shell: bash -l {0}
      run: |
        pip install ${{ inputs.reinstall-target }}

    - name: Run notebooks through pytest
      working-directory: ${{ inputs.working-dir }}
      shell: bash -l {0}
      env:
        PYTEST_ADDOPTS: >-
          --color=yes
          --pyargs=idaes_examples.notebooks.docs
          --pyargs=idaes_examples.notebooks.active
          --nbmake
          --nbmake-timeout=${{ inputs.notebook-cell-exec-timeout }}
          -n=auto
          --durations=0
      run: |
        rm -rf *  # ensure directory is empty
        pytest
