name: Run integration tests

on:
  # for the moment, this workflow needs to be triggered manually
  workflow_dispatch:
  repository_dispatch:
    # to run this, send a POST API call at repos/IDAES/idaes-pse/dispatches with the specified event_type
    # e.g. `gh repos/IDAES/idaes-pse/dispatches -F event_type=integration_tests_requested`
    types: [integration_tests_requested]
  schedule:
    # run daily at 5:00 am UTC (12 am ET/9 pm PT)
    - cron: '0 5 * * *'
    - cron: '30 7 * * *'

defaults:
  run:
    shell: bash

jobs:
  integration:
    name: Integration tests (py=${{ matrix.python-version }}, os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      # if fail-fast == true (the default), jobs for the remaining values in the matrix are cancelled
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
        os:
          - ubuntu-18.04
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install idaes and dependencies
        run: |
          python -m pip --no-cache-dir install --progress-bar off .[dev]
      - name: Install extensions
        run: |
          idaes get-extensions --verbose
          find $(idaes data-directory) -ls
          PATH=$PATH:$(idaes bin-directory)
          if [ "$RUNNER_OS" == "Windows" ]; then
              ipopt.exe -v
          else
              ipopt -v
          fi
      - name: Run idaes-pse integration tests
        run: |
          PATH=$PATH:$(idaes bin-directory)
          pytest -m integration idaes/
      - name: Fetch examples-pse
        run: |
          git clone https://github.com/IDAES/examples-pse.git
      - name: Run examples-pse tests
        run: |
          PATH=$PATH:$(idaes bin-directory)
          cd examples-pse
          pytest
