name: Validate code using static analysis

on:
  workflow_dispatch:
  pull_request:
  push:
    # only run this if there's any python file among those being pushed
    # paths:
    #   - '**.py'

jobs:
  pylint:
    name: Run pylint (errors only)
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install pylint dependencies
      run: |
        # TODO pylint and astroid versions will need to be pinned
        python -m pip --no-cache-dir install --progress-bar off pylint
        # in general the package being pylinted does not need to be installed to run pylint on it
        # but in our case the pylint plugin needs to be able to import some code from idaes and pyomo
        python -m pip --no-cache-dir install --progress-bar off .
    - name: Run pylint
      run: |
        pylint -E --ignore-patterns="test_.*" idaes || true

