name: Installation and non-integration tests

on:
  workflow_dispatch:
  pull_request:
  push:
    # uncomment this to run this only if files in the root Python package directory have been changed
    # paths:
    #   - 'idaes/**'

defaults:
  run:
    shell: bash

jobs:
  idaes-pse:
    name: Install and test (py=${{ matrix.python-version }}, os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      # if fail-fast == true (the default), jobs for the remaining values in the matrix are cancelled
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
        os:
          - ubuntu-18.04
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        # if: ${{ runner.os == 'Linux' }}
        run: |
          python -m pip install --progress-bar off -r requirements.txt
      - name: Display IDAES version
        run: |
          idaes --version
      - name: Install IDAES extensions
        run: |
          idaes get-extensions --verbose
          ipopt -v
        # adding "ipopt -v" causes this step to fail
        # so we add an exception to continue with the rest of the job in case of failure
        continue-on-error: true
      - name: Run tests (excluding integration)
        run: |
          pytest -c pytest.ini -m 'not integration' idaes/
      # TODO: pytest --cov
      # TODO: coveralls (coverage report)
